import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/providers";
import TopNav from "@/components/navBar/topnav";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Match Me",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="px-5 text-white bg-[#050505]">
        <Providers>
          <TopNav />
          <main className="container mx-auto ">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
